### ISSUE TITLE
elasticSearch 데이터 삽입 시 id 설정

### ISSUE THREAD

**Issue by devyuseon** [2E2I/donation-crawler#1]
- json파일을 통째로 삽입하게 되면 id에 임의의 값이 할당됨.
- id를 분리하려면 json파일에서 반복문 돌면서 `bulk`가 아닌 `es.index()` 메서드를 써야할것 같은데 시간적으로 괜찮은지? 모르겠습니다..
- bulk를 이용해서 할 방법이 있는지도 알아봐야함

@im-shung 의견 적극 받음🙋‍♀️

**Comment by im-shung** [comment]
https://blog.ruanbekker.com/blog/2018/04/29/using-the-bulk-api-with-elasticsearch/
이런 방식으로 접근해도 될란지..?? 일단 메모

**Comment by devyuseon** [comment]
이슈번호 잘못적었따 ;-; 무시해주세요..
