### ISSUE TITLE
캠페인 카테고리 되살리기  

### ISSUE THREAD

**Issue by im-shung** [2E2I/donation-crawler#16]
[카테고리 분류 과정](https://github.com/2E2I/mamomo-server/issues/27#issue-1166434210)

**해피빈에서 할 일**
-
- `아동•청소년` ➡️ `아동|청소년`
- `어르신`
- `장애인`
- `기타` ➡️ `어려운이웃` 
- `다문화`
- `지구촌`
- `가족•여성` ➡️ `가족|여성`
- `시민사회`➡️ `우리사회`
- `동물`
- `환경` 

**카카오같이가치에서 할 일**
-
- `아동|청소년` 
- `실버세대` ➡️`어르신`
- `장애인` 
- `어려운이웃`
- `이주민|다문화`➡️  `다문화` 
- `지구촌` 
- `여성` ➡️  `가족|여성` 
- `우리사회` 
- `동물`
- `환경`

**Comment by devyuseon** [comment]
카테고리 두가지있는거 내가 보기엔 `•` 보다 `|` 가 더 깔끔해보이는데 @im-shung 는 어때??

**Comment by im-shung** [comment]
오키 근데 언니 카테고리 작업 안하고 있지...?? 내가 지금 push 하려고 했는데ㅋㅋㅋ

**Comment by devyuseon** [comment]
커밋 하나 했는데!.. 나두 충돌날까봐 캠페인클래스에 카테고리만 추가하구 딴건 안건드렸으 이제 해피빈 하려고

**Comment by im-shung** [comment]
엇 아냐 나 다 했어,, 안 해도 됑

**Comment by devyuseon** [comment]
? 아니 나 이미 푸시햇어..!

**Comment by im-shung** [comment]
아니 해피빈 안 해도 된다구 내가 해피빈까지 했어

**Comment by devyuseon** [comment]
헉 오키 수고했어.!! 😅😅
